### PR TITLE
Do not report missing docs for exceptions

### PR DESCRIPTION
**Pull request by pnezis**
In case of a `defexception` the convention is to not have a `moduledoc`,
struct type spec can be ignored as well since the `__struct__` is
injected from the `defexception` macro.

### CODE REVIEW

**Comment by akoutmos** [comment]
Thanks for opening up this PR! I can get on board with the typespec skipping...but personally I usually add moduledocs for exceptions so codebase readers know when that exception can occur (sort of how it is done in Ecto https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/exceptions.ex). Thoughts?

**Comment by pnezis** [comment]
@akoutmos I also add moduledocs to exceptions but in most projects (elixir itself included) this is not the case. I could add a config option for defining if the moduledoc in exceptions is required or not. What do you think?

**Comment by akoutmos** [comment]
That's a fair point with regards to the Elixir codebase itself. I'd be good with a config flag for moduledoc enforcement on exception modules. Think that get's use to a best of both worlds scenario :).

**Comment by pnezis** [comment]
@akoutmos I added an `exception_moduledoc_required` config option which defaults to `true`. 

Also included in the PR:

- A fix for `mix doctor.explain`  (currently it does not support command line args like `--config-file` )
- Fix the typespec of `ModuleReport.module`, it was set to `module()` but it actually is a `String.t()`

Regarding the implementation of the extra option I considered several approaches:

- Add an `is_exception` member to the `ModuleInformation` class which will be copied to the `ModuleReport`
- Make the `is_exception?` function in `ModuleInformation` public and call it from the reporters

I finally settled with adding a generic `properties` field in `ModuleInformation` which is copied to `ModuleReport`. The main reasoning for this is extensibility. In the future some extra corner cases may need to be handled, or some extra checks may need to be added, and a generic `properties` field would make any future enhancement of such kind easy. Thoughts?

**Comment by akoutmos** [comment]
Really like all the changes that you have put together @pnezis! I'll pull this down and play with it either today or tomorrow and if all looks good I'll merge it in. Thanks!

**Comment by pnezis** [comment]
Thanks for merging this @akoutmos

**Comment by akoutmos** [comment]
Thank *you* for the awesome contribution :). I'll cut a new release in the coming days.

**Pull request merged**
